stages:
  - build
  - test
  - deploy

.node:
  image: node:16

  before_script:
    - '[[ -d node_modules ]] || npm ci --progress=false'

  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - node_modules

.deploy:
  stage: deploy
  image: juty/php-runner-7.4:v1.0.1
  before_script:
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null


deploy_production:
  extends: .deploy
  script:
    - /root/.composer/vendor/bin/dep deploy main --tag=$CI_COMMIT_REF_NAME -vvv
  only:
    - main
  variables:
    PHP_PATH: /usr/bin/php8.0
    HOSTNAME: $DEPLOY_HOSTNAME
    USERNAME: $DEPLOY_USERNAME
    DEPLOY_PATH: $DEPLOY_PATH
    NOVA_USERNAME: $NOVA_USERNAME
    NOVA_LICENSE_KEY: $NOVA_LICENSE_KEY
